### ISSUE TITLE
Cannot run command standard in a React native project

### ISSUE THREAD

**Issue by ansonyao** [standard/standard#1012]
I just installed today.
When I run command standard. The following error shows up. 

RangeError: Line number out of range (line 30 requested, but only 29 lines present).
    at SourceCode.getIndexFromLoc (/usr/local/lib/node_modules/standard/node_modules/eslint/lib/util/source-code.js:389:19)
    at Object.fix (/usr/local/lib/node_modules/standard/node_modules/eslint/lib/rules/no-multiple-empty-lines.js:116:52)
    at RuleContext.report (/usr/local/lib/node_modules/standard/node_modules/eslint/lib/rule-context.js:127:34)
    at Program:exit.allLines.reduce.concat.reduce (/usr/local/lib/node_modules/standard/node_modules/eslint/lib/rules/no-multiple-empty-lines.js:108:37)
    at Array.reduce (native)
    at EventEmitter.Program:exit (/usr/local/lib/node_modules/standard/node_modules/eslint/lib/rules/no-multiple-empty-lines.js:93:22)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.applySelector (/usr/local/lib/node_modules/standard/node_modules/eslint/lib/util/node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (/usr/local/lib/node_modules/standard/node_modules/eslint/lib/util/node-event-generator.js:294:22)

**Comment by Flet** [comment]
This looks like its related to #997 and #833, which is due to an `eslint` bug.

We just released a beta for the next version of `standard`, which includes upgrading `eslint`, Can you try installing `npm install standard@beta` and see if it fixes it?

**Comment by feross** [comment]
🗣 Standard 11 is released! Run `npm install standard@latest --save-dev` to update to the latest version. This will also update the version in `package.json` ✨

Changelog: https://github.com/standard/standard/blob/master/CHANGELOG.md#1100---2018-02-18
