### ISSUE TITLE
The latest release of is-my-json-valid breaks standard

### ISSUE THREAD

**Issue by tsujigiri** [standard/standard#1030]
Since is-my-json-valid released version 2.17.0, I get the following error when running standard:

```
/home/helge/.node_modules/lib/node_modules/standard/node_modules/is-my-json-valid/index.js:366
      visit(name+'['+i+']', node.items, reporter, filter, schemaPath.concat('items'))
                                                                     ^

TypeError: Cannot read property 'concat' of undefined
    at visit (/home/helge/.node_modules/lib/node_modules/standard/node_modules/is-my-json-valid/index.js:366:70)
    at /home/helge/.node_modules/lib/node_modules/standard/node_modules/is-my-json-valid/index.js:416:9
    at Array.forEach (<anonymous>)
    at visit (/home/helge/.node_modules/lib/node_modules/standard/node_modules/is-my-json-valid/index.js:409:18)
    at /home/helge/.node_modules/lib/node_modules/standard/node_modules/is-my-json-valid/index.js:543:9
    at Array.forEach (<anonymous>)
    at visit (/home/helge/.node_modules/lib/node_modules/standard/node_modules/is-my-json-valid/index.js:540:31)
    at compile (/home/helge/.node_modules/lib/node_modules/standard/node_modules/is-my-json-valid/index.js:565:3)
    at visit (/home/helge/.node_modules/lib/node_modules/standard/node_modules/is-my-json-valid/index.js:340:16)
    at /home/helge/.node_modules/lib/node_modules/standard/node_modules/is-my-json-valid/index.js:416:9
```

**Comment by Kikobeats** [comment]
same behavior on my projects.

Looks like is not ignoring `node_modules` by default 🤔

**Comment by obdulia-losantos** [comment]
Including `"is-my-json-valid": "~2.16.0"` in `package.json` fixes it. At least in my case.

**Comment by LinusU** [comment]
This was me 🙈 sorry about that!

It has been fixed upstream now, and the broken version have been deprecated on npm.

Just reinstalling or manually upgrading is-my-json-valid to 2.17.1 (`npm install is-my-json-valid@2.17.1`) should fix it 👌

**Comment by jameshhx** [comment]
Thanks @LinusU! 👍
