### ISSUE TITLE
Cannot read property 'hashOfConfig' of undefined

### ISSUE THREAD

**Issue by steabert** [standard/standard#1083]
After installing and running `standard`, I get:

```
$ yarn standard
yarn run v1.3.2
$ /home/.../node_modules/.bin/standard
standard: Unexpected linter output:

TypeError: Cannot read property 'hashOfConfig' of undefined
    at fileList.map.fileInfo (/home/.../node_modules/eslint/lib/cli-engine.js:532:71)
    at Array.map (<anonymous>)
    at CLIEngine.executeOnFiles (/home/.../node_modules/eslint/lib/cli-engine.js:518:34)
    at /home/.../node_modules/standard-engine/index.js:111:61
    at /home/.../node_modules/deglob/index.js:51:12
    at end (/home/.../node_modules/run-parallel/index.js:16:15)
    at done (/home/.../node_modules/run-parallel/index.js:20:10)
    at each (/home/.../node_modules/run-parallel/index.js:26:7)
    at /home/.../node_modules/run-parallel/index.js:41:37
    at f (/home/.../node_modules/once/once.js:25:25)
```

**Comment by steabert** [comment]
It was a problem with eslint not being able to handle a symbolic link pointing to a non-existing file. I will put an issue with eslint instead.
