### ISSUE TITLE
Template string as object key is broken

### ISSUE THREAD

**Issue by Kikobeats** [standard/standard#1116]
Hello,

I noted that using an interpolate string as an object key break the linter.

### Example of code

```js
'use strict'

const foo = 'foo'

const routes = {
  [`${foo}`]: 'foobar'
}
```

### Linter output

```bash
❯ npx standard test.js
standard: Unexpected linter output:

TypeError: Cannot read property 'range' of null
    at SourceCode.getTokenBefore (/Users/josefranciscoverdugambin/audiense/web/node_modules/standard/node_modules/eslint/lib/token-store/index.js:303:18)
    at checkSpacingBefore (/Users/josefranciscoverdugambin/audiense/web/node_modules/standard/node_modules/eslint/lib/rules/template-curly-spacing.js:52:42)
    at TemplateElement (/Users/josefranciscoverdugambin/audiense/web/node_modules/standard/node_modules/eslint/lib/rules/template-curly-spacing.js:117:17)
    at listeners.(anonymous function).forEach.listener (/Users/josefranciscoverdugambin/audiense/web/node_modules/standard/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/josefranciscoverdugambin/audiense/web/node_modules/standard/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/Users/josefranciscoverdugambin/audiense/web/node_modules/standard/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/josefranciscoverdugambin/audiense/web/node_modules/standard/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/Users/josefranciscoverdugambin/audiense/web/node_modules/standard/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/Users/josefranciscoverdugambin/audiense/web/node_modules/standard/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)

If you think this is a bug in `standard`, open an issue: https://github.com/standard/standard/issues
```

### Environment info

```
npx standard --version
11.0.1

npx node --version
v9.11.1

npx npm --version
3.10.10
```

**Comment by jdkschang** [comment]
@Kikobeats This seems to be an `babel` issue--specifically regarding `babel-eslint` and types.
[See here](https://github.com/babel/babel-eslint/issues/530#issuecomment-354242702) for more details

**Comment by feross** [comment]
This issue seems to be fixed in babel upstream now, so I am going to close this issue: https://github.com/babel/babel-eslint/issues/530#issuecomment-354242702
