### ISSUE TITLE
Unexpected linter output

### ISSUE THREAD

**Issue by darioajr** [standard/standard#1142]
"babel-eslint": "7.1.1",
"standard": "10.0.2",
"lint": "standard --verbose | snazzy"
![captura de tela 2018-05-29 as 12 16 02](https://user-images.githubusercontent.com/7606/40668129-1ac624f0-633a-11e8-9bf2-c117ee1786fe.png)

Mac OS 10.13.4
Node v9.11.1
Npm 5.6.0
npm run lint -s

standard: Unexpected linter output:

RangeError: Line number out of range (line 11 requested, but only 10 lines present).
at SourceCode.getIndexFromLoc (/Users/dario/Documents/srm-app/node_modules/eslint/lib/util/source-code.js:389:19)
at Object.fix (/Users/dario/Documents/srm-app/node_modules/eslint/lib/rules/no-multiple-empty-lines.js:116:52)
at RuleContext.report (/Users/dario/Documents/srm-app/node_modules/eslint/lib/rule-context.js:127:34)
at Program:exit.allLines.reduce.concat.reduce (/Users/dario/Documents/srm-app/node_modules/eslint/lib/rules/no-multiple-empty-lines.js:108:37)
at Array.reduce ()
at EventEmitter.Program:exit (/Users/dario/Documents/srm-app/node_modules/eslint/lib/rules/no-multiple-empty-lines.js:93:22)
at EventEmitter.emit (events.js:185:15)
at NodeEventGenerator.applySelector (/Users/dario/Documents/srm-app/node_modules/eslint/lib/util/node-event-generator.js:265:26)
at NodeEventGenerator.applySelectors (/Users/dario/Documents/srm-app/node_modules/eslint/lib/util/node-event-generator.js:294:22)
at NodeEventGenerator.leaveNode (/Users/dario/Documents/srm-app/node_modules/eslint/lib/util/node-event-generator.js:317:14)

If you think this is a bug in standard, open an issue: https://github.com/feross/standard/issues

**Comment by darioajr** [comment]
React Native app

**Comment by darioajr** [comment]
[FixtureHubApi.js.zip](https://github.com/standard/standard/files/2065982/FixtureHubApi.js.zip)

**Comment by darioajr** [comment]
standard --fix don't fix this, show the same error.

**Comment by darioajr** [comment]
> @darioajr if you're still receiving this issue please refer to this [babel issue](https://github.com/babel/babel-eslint/issues/530#issuecomment-414224861).
> 
> can someone close and merge this with issue #1116


I also created an issue in babel.
