### ISSUE TITLE
TypeError: Cannot read property 'range' of null

### ISSUE THREAD

**Issue by hitesh2067** [standard/standard#1222]
standard 12.0.1

MacOS 10.14.1  npm 6.4.1 node v10.12.0

on standard --fix command this error come

standard: Unexpected linter output:

TypeError: Cannot read property 'range' of null
    at SourceCode.getTokenBefore (/Users/hiteshgupta/WebstormProjects/aperio_ui_core_ehr/node_modules/standard/node_modules/eslint/lib/token-store/index.js:303:18)
    at checkSpacingBefore (/Users/hiteshgupta/WebstormProjects/aperio_ui_core_ehr/node_modules/standard/node_modules/eslint/lib/rules/template-curly-spacing.js:52:42)
    at TemplateElement (/Users/hiteshgupta/WebstormProjects/aperio_ui_core_ehr/node_modules/standard/node_modules/eslint/lib/rules/template-curly-spacing.js:117:17)
    at listeners.(anonymous function).forEach.listener (/Users/hiteshgupta/WebstormProjects/aperio_ui_core_ehr/node_modules/standard/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/hiteshgupta/WebstormProjects/aperio_ui_core_ehr/node_modules/standard/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/Users/hiteshgupta/WebstormProjects/aperio_ui_core_ehr/node_modules/standard/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/hiteshgupta/WebstormProjects/aperio_ui_core_ehr/node_modules/standard/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/Users/hiteshgupta/WebstormProjects/aperio_ui_core_ehr/node_modules/standard/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/Users/hiteshgupta/WebstormProjects/aperio_ui_core_ehr/node_modules/standard/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)

If you think this is a bug in `standard`, open an issue: https://github.com/standard/standard/issues
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @sourcefuse/aperio@1.8.14 standard-fix: `standard --fix`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @sourcefuse/aperio@1.8.14 standard-fix script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by toltarisa** [comment]
did you saw that solve at here ? Check it out https://github.com/babel/babel-eslint/issues/530

**Comment by hitesh2067** [comment]
Thanks, @toltarisa  it helped. 
Sorry for late reply I am closing this issue.
