### ISSUE TITLE
Error with 'Unexpected linter output' Function.keys

### ISSUE THREAD

**Issue by aravindkumaremis** [standard/standard#1250]
**What version of standard?**
```
$ standard --version
12.0.1
```
**What operating system, Node.js, and npm version?**
```
$ node --version
v11.8.0

$ npm --version
6.8.0
```
**What actually happened?**
```
$ ./node_modules/standard/bin/cmd.js test/api/*
standard: Unexpected linter output:

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.keys (myproject/node_modules/flat-cache/cache.js:52:19)
    at removeNotFoundFiles (myproject/node_modules/file-entry-cache/cache.js:18:35)
    at Object.create (myproject/node_modules/file-entry-cache/cache.js:31:5)
    at new LintResultCache (myproject/node_modules/eslint/lib/util/lint-result-cache.js:62:46)
    at new CLIEngine (myproject/node_modules/eslint/lib/cli-engine.js:430:37)
    at myproject/node_modules/standard-engine/index.js:119:16
    at myproject/node_modules/deglob/index.js:51:12
    at end (myproject/node_modules/run-parallel/index.js:18:15)
    at done (myproject/node_modules/run-parallel/index.js:22:10)

If you think this is a bug in `standard`, open an issue: https://github.com/standard/standard/issues

```

Added the following in package.json

```
  "devDependencies": {
    "standard": "^12.0.1"
  },
  "scripts": {
    "test": "standard && node my-tests.js",
    "pretest": "./node_modules/standard/bin/cmd.js"
  }
```
Error:

```
$ npm test

> atlas@1.0.0 pretest myproject
> ./node_modules/standard/bin/cmd.js

standard: Unexpected linter output:

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.keys (myproject/node_modules/flat-cache/cache.js:52:19)
    at removeNotFoundFiles (myproject/node_modules/file-entry-cache/cache.js:18:35)
    at Object.create (myproject/node_modules/file-entry-cache/cache.js:31:5)
    at new LintResultCache (myproject/node_modules/eslint/lib/util/lint-result-cache.js:62:46)
    at new CLIEngine (myproject/node_modules/eslint/lib/cli-engine.js:430:37)
    at myproject/node_modules/standard-engine/index.js:119:16
    at myproject/node_modules/deglob/index.js:51:12
    at end (myproject/node_modules/run-parallel/index.js:18:15)
    at done (myproject/node_modules/run-parallel/index.js:22:10)

If you think this is a bug in `standard`, open an issue: https://github.com/standard/standard/issues
npm ERR! Test failed.  See above for more details.
```

**Comment by AngeIII** [comment]
@aravindkumaremis I have same issue, is there any solution you found?

**Comment by AngeIII** [comment]
```
$ standard --version && standard
12.0.1
standard: Unexpected linter output:

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.keys (/home/pavel/Data/visualcomposer/node_modules/flat-cache/cache.js:52:19)
    at removeNotFoundFiles (/home/pavel/Data/visualcomposer/node_modules/file-entry-cache/cache.js:18:35)
    at Object.create (/home/pavel/Data/visualcomposer/node_modules/file-entry-cache/cache.js:31:5)
    at new LintResultCache (/home/pavel/Data/visualcomposer/node_modules/eslint/lib/util/lint-result-cache.js:62:46)
    at new CLIEngine (/home/pavel/Data/visualcomposer/node_modules/eslint/lib/cli-engine.js:476:37)
    at /home/pavel/Data/visualcomposer/node_modules/standard-engine/index.js:119:16
    at /home/pavel/Data/visualcomposer/node_modules/deglob/index.js:51:12
    at end (/home/pavel/Data/visualcomposer/node_modules/run-parallel/index.js:18:15)
    at done (/home/pavel/Data/visualcomposer/node_modules/run-parallel/index.js:22:10)

If you think this is a bug in `standard`, open an issue: https://github.com/standard/standard/issues
```

**Comment by ahslr** [comment]
@AngeIII @aravindkumaremis 
Delete .eslintcache file. It is stored in the root of your project by default. I think this should work for now.

**Comment by zenboss** [comment]
> @AngeIII @aravindkumaremis
> Delete .eslintcache file. It is stored in the root of the project by default. I think this should work for now.

It's useful for me, thank you.

**Comment by AngeIII** [comment]
I don't have such file (.eslintcache), also I noticed that with NPM install it works fine, but with `yarn install` it doesn't.
