### ISSUE TITLE
Failed to load plugin typescript: Cannot find module 'eslint-plugin-typescript'

### ISSUE THREAD

**Issue by maggot99999** [standard/standard#1289]
### What version of standard?
**standard@12.0.1**

### What operating system, Node.js, and npm version?
**npm@6.9.0**

###  What did you expect to happen?
**node@10.15.3**

### What actually happened?

> **npm ls -D --depth 0**                                                                                                                                                                       
```
test3@1.0.0 C:\Users\m9\repos\test3
+-- @typescript-eslint/eslint-plugin@1.9.0
+-- @typescript-eslint/experimental-utils@1.9.0
+-- @typescript-eslint/parser@1.9.0
+-- eslint@5.16.0
+-- standard@12.0.1
`-- typescript@3.5.1
```
---
> **standard --parser @typescript-eslint/parser --plugin typescript \*.ts**
```
standard: Unexpected linter output:
 
Error: Failed to load plugin typescript: Cannot find module 'eslint-plugin-typescript'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at Plugins.load (C:\Users\m9\AppData\Roaming\npm\node_modules\standard\node_modules\eslint\lib\config\plugins.js:96:29)
    at Array.forEach (<anonymous>)
    at Plugins.loadAll (C:\Users\m9\AppData\Roaming\npm\node_modules\standard\node_modules\eslint\lib\config\plugins.js:157:21)
    at Config.getConfig (C:\Users\m9\AppData\Roaming\npm\node_modules\standard\node_modules\eslint\lib\config.js:344:26)
    at hashOfConfigFor (C:\Users\m9\AppData\Roaming\npm\node_modules\standard\node_modules\eslint\lib\util\lint-result-cache.js:31:33)
    at LintResultCache.getCachedLintResults (C:\Users\m9\AppData\Roaming\npm\node_modules\standard\node_modules\eslint\lib\util\lint-result-cache.js:86:30)
    at fileList.map.fileInfo (C:\Users\m9\AppData\Roaming\npm\node_modules\standard\node_modules\eslint\lib\cli-engine.js:520:59)
    at Array.map (<anonymous>)

If you think this is a bug in `standard`, open an issue: https://github.com/standard/standard/issues
```
---
> **npm install eslint-plugin-typescript --save-dev**
```
npm WARN deprecated eslint-plugin-typescript@0.14.0: Deprecated: Use @typescript-eslint/eslint-plugin instead
npm WARN test3@1.0.0 No description
npm WARN test3@1.0.0 No repository field.

+ eslint-plugin-typescript@0.14.0
added 2 packages from 2 contributors and audited 585 packages in 3.773s
found 0 vulnerabilities
```
---
> **standard --parser @typescript-eslint/parser --plugin typescript \*.ts**
```
standard: Unexpected linter output:

Error: Failed to load plugin typescript: Cannot find module 'eslint-plugin-typescript'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at Plugins.load (C:\Users\m9\AppData\Roaming\npm\node_modules\standard\node_modules\eslint\lib\config\plugins.js:96:29)
    at Array.forEach (<anonymous>)
    at Plugins.loadAll (C:\Users\m9\AppData\Roaming\npm\node_modules\standard\node_modules\eslint\lib\config\plugins.js:157:21)
    at Config.getConfig (C:\Users\m9\AppData\Roaming\npm\node_modules\standard\node_modules\eslint\lib\config.js:344:26)
    at hashOfConfigFor (C:\Users\m9\AppData\Roaming\npm\node_modules\standard\node_modules\eslint\lib\util\lint-result-cache.js:31:33)
    at LintResultCache.getCachedLintResults (C:\Users\m9\AppData\Roaming\npm\node_modules\standard\node_modules\eslint\lib\util\lint-result-cache.js:86:30)
    at fileList.map.fileInfo (C:\Users\m9\AppData\Roaming\npm\node_modules\standard\node_modules\eslint\lib\cli-engine.js:520:59)
    at Array.map (<anonymous>)

If you think this is a bug in `standard`, open an issue: https://github.com/standard/standard/issues
```
---
> **npm ls -D --depth 0**
```
test3@1.0.0 C:\Users\m9\repos\test3
+-- @typescript-eslint/eslint-plugin@1.9.0
+-- @typescript-eslint/experimental-utils@1.9.0
+-- @typescript-eslint/parser@1.9.0
+-- eslint@5.16.0
+-- eslint-plugin-typescript@0.14.0
+-- standard@12.0.1
`-- typescript@3.5.1
```

### File Structrure
```
. 
|-- index.ts 
|-- package-lock.json
`-- package.json 
```

**Comment by maggot99999** [comment]
It tried to use global depency which couldn't find global eslint-plugin-typescript which was not installed.
After ```npm i -g eslint-plugin-typescript @typescript-eslint/parser``` it started to work fine
