### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by jfoclpf** [standard/standard#1334]
**What version of standard?**
13.0.2

**What operating system, Node.js, and npm version?**

```
npm --version 
6.10.1

node --version 
v9.4.0

```

**What did you expect to happen?**

check for errors

I'm running local bin

`node_modules/.bin/standard "src/**/*.js"`

or global

`standard "src/**/*.js"`

**What actually happened?**

```
node_modules/.bin/standard "src/**/*.js"
standard: Unexpected linter output:

RangeError: Maximum call stack size exceeded
Occurred while linting /home/jfolpf/autocosts/src/client/pdf/CN/vfs_fonts.js:2
    at RegExp.[Symbol.match] (<anonymous>)
    at String.match (native)
    at Literal (/home/jfolpf/autocosts/node_modules/eslint/lib/rules/no-octal-escape.js:35:40)
    at listeners.(anonymous function).forEach.listener (/home/jfolpf/autocosts/node_modules/eslint/lib/linter/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/home/jfolpf/autocosts/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/jfolpf/autocosts/node_modules/eslint/lib/linter/node-event-generator.js:253:26)
    at NodeEventGenerator.applySelectors (/home/jfolpf/autocosts/node_modules/eslint/lib/linter/node-event-generator.js:282:22)
    at NodeEventGenerator.enterNode (/home/jfolpf/autocosts/node_modules/eslint/lib/linter/node-event-generator.js:296:14)
    at CodePathAnalyzer.enterNode (/home/jfolpf/autocosts/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:645:23)

```

But when running the equivalent eslint, 

`node_modules/.bin/eslint -c test/.eslintrc.json "src/**/*.js" `

it does work

It seems it is giving an error on some fonts file. Is there a way to ignore files in CLI?

**Comment by jfoclpf** [comment]
Found the issue
https://standardjs.com/#how-do-i-ignore-files

You may close this thread!

PS: nonetheless you may consider this as a bug, since eslint CLI is not throwing an error whilst standard CLI is.

**Comment by feross** [comment]
Interesting. Are you sure that you're using the same version of `eslint` in both cases?

**Comment by jfoclpf** [comment]
I'm using on both cases the latest versions available on npm.
