### ISSUE TITLE
Regression introduced in 13.0.0: "TypeError: Cannot get property 'range' of null"

### ISSUE THREAD

**Issue by matthewadams** [standard/standard#1450]
**What version of this package are you using?**
`14.3.1`

**What operating system, Node.js, and npm version?**
macOS 10.14.6

```
$ node --version
v10.17.0
```

```
$ npm --version
6.11.3
```

**What happened?**
Upgraded all deps to latest versions as of this issue report & got failure:
```
> @scispike/nodejs-support@2.0.2-rc.0 lint /Users/matthewadams/dev/scispike/nodejs-support
> standard --verbose 'src/**/*.js'

standard: Unexpected linter output:

TypeError: Cannot read property 'range' of null
Occurred while linting /Users/matthewadams/dev/scispike/nodejs-support/src/main/entities/DatePeriod.js:27
    at SourceCode.getTokenBefore (/Users/matthewadams/dev/scispike/nodejs-support/node_modules/eslint/lib/source-code/token-store/index.js:303:18)
    at checkSpacingBefore (/Users/matthewadams/dev/scispike/nodejs-support/node_modules/eslint/lib/rules/template-curly-spacing.js:60:42)
    at TemplateElement (/Users/matthewadams/dev/scispike/nodejs-support/node_modules/eslint/lib/rules/template-curly-spacing.js:119:17)
    at listeners.(anonymous function).forEach.listener (/Users/matthewadams/dev/scispike/nodejs-support/node_modules/eslint/lib/linter/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/matthewadams/dev/scispike/nodejs-support/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/matthewadams/dev/scispike/nodejs-support/node_modules/eslint/lib/linter/node-event-generator.js:253:26)
    at NodeEventGenerator.applySelectors (/Users/matthewadams/dev/scispike/nodejs-support/node_modules/eslint/lib/linter/node-event-generator.js:282:22)
    at NodeEventGenerator.enterNode (/Users/matthewadams/dev/scispike/nodejs-support/node_modules/eslint/lib/linter/node-event-generator.js:296:14)
    at CodePathAnalyzer.enterNode (/Users/matthewadams/dev/scispike/nodejs-support/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:646:23)
```

`package.json` dependencies are the following:

```
  "dependencies": {
    "@babel/polyfill": "7.7.0",
    "@scispike/aspectify": "1.0.0",
    "bunyan": "1.8.12",
    "bunyaner": "1.1.0",
    "enumify": "1.0.4",
    "lodash.merge": "4.6.2",
    "moment": "2.24.0",
    "moment-timezone": "0.5.27",
    "mutrait": "1.0.0",
    "uuid": "3.3.3"
  },
  "devDependencies": {
    "@babel/cli": "7.7.0",
    "@babel/core": "7.7.0",
    "@babel/plugin-proposal-class-properties": "7.7.0",
    "@babel/plugin-proposal-decorators": "7.7.0",
    "@babel/plugin-proposal-optional-chaining": "7.6.0",
    "@babel/plugin-proposal-throw-expressions": "7.2.0",
    "@babel/preset-env": "7.7.1",
    "@babel/register": "7.7.0",
    "acorn": "7.1.0",
    "babel-eslint": "10.0.3",
    "chai": "4.2.0",
    "cls-hooked": "4.2.2",
    "copyfiles": "2.1.1",
    "dirty-chai": "2.0.1",
    "fs-extra": "8.1.0",
    "intercept-stdout": "0.1.2",
    "mocha": "6.2.2",
    "npm-run-all": "4.1.5",
    "nyc": "14.1.1",
    "standard": "14.3.1",
    "zone.js": "0.10.2"
  },
```
Traced it back to `standard@13.0.0`; no error with with `standard@12.0.1`.

**What did you expect to happen?**
Successful linting.

**Are you willing to submit a pull request to fix this bug?**
Since this is a dev dependency, prolly not.  No time.  Must focus on prod issues.

**Comment by matthewadams** [comment]
More info:  strangely, while 12.0.1 worked on my mac, it failed in CI on travis-ci.com:  https://travis-ci.com/SciSpike/nodejs-support/builds/135216135

**Comment by mightyiam** [comment]
Thank you for the issue, @matthewadams. Whatever it was, it seems  to have been resolved. Probably somewhere down the dependency tree.

https://github.com/SciSpike/nodejs-support/pull/12

**Comment by matthewadams** [comment]
Hi @mightyiam looks like it's still a problem.  I've updated dependencies in `master` & it's still failing, but _not_ on macOS, only on *n*x (see docker build output below).  It appears that it's related to upgrading `babel-eslint`.  If you look at the [build history](https://travis-ci.com/SciSpike/nodejs-support/builds) of the project, my last commit before upgrading `babel-eslint`, which upgraded everything _but_ `babel-eslint`, succeeded.  When I upgraded `babel-eslint`, `standard` failed:  https://travis-ci.com/SciSpike/nodejs-support/builds/136353983

I'll see if I can pin it down to a particular version of `babel-eslint` and report back.

```
$ docker run --rm -it -v $PWD:/app -w /app node:10.17.0 npm run build

> @scispike/nodejs-support@2.1.0-pre.0 build /app
> npm install && npm test


> dtrace-provider@0.8.7 install /app/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

make: Entering directory '/app/node_modules/dtrace-provider/build'
  TOUCH Release/obj.target/DTraceProviderStub.stamp
make: Leaving directory '/app/node_modules/dtrace-provider/build'

> core-js@2.6.10 postinstall /app/node_modules/@babel/polyfill/node_modules/core-js
> node postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js@2.6.9 postinstall /app/node_modules/@scispike/aspectify/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 906 packages from 822 contributors and audited 5163 packages in 88.114s
found 16 vulnerabilities (1 moderate, 15 high)
  run `npm audit fix` to fix them, or `npm audit` for details

> @scispike/nodejs-support@2.1.0-pre.0 test /app
> run-s transpile unit-integration lint


> @scispike/nodejs-support@2.1.0-pre.0 transpile /app
> run-s transpile-main transpile-test


> @scispike/nodejs-support@2.1.0-pre.0 transpile-main /app
> babel --delete-dir-on-start --verbose --out-dir lib/main --copy-files src/main

src/main/context/ClsHookedContext.js -> lib/main/context/ClsHookedContext.js
src/main/context/ZoneJsContext.js -> lib/main/context/ZoneJsContext.js
src/main/context/index.js -> lib/main/context/index.js
src/main/entities/DatePeriod.js -> lib/main/entities/DatePeriod.js
src/main/entities/Identifiable.js -> lib/main/entities/Identifiable.js
src/main/entities/Period.js -> lib/main/entities/Period.js
src/main/entities/Persistable.js -> lib/main/entities/Persistable.js
src/main/entities/Recurrence.js -> lib/main/entities/Recurrence.js
src/main/entities/index.js -> lib/main/entities/index.js
src/main/enums/DayOfWeek.js -> lib/main/enums/DayOfWeek.js
src/main/enums/Enumeration.js -> lib/main/enums/Enumeration.js
src/main/enums/ResponseStatus.js -> lib/main/enums/ResponseStatus.js
src/main/enums/TimeUnit.js -> lib/main/enums/TimeUnit.js
src/main/enums/index.js -> lib/main/enums/index.js
src/main/errors/AlreadyInitializedError.js -> lib/main/errors/AlreadyInitializedError.js
src/main/errors/ClassNotExtendableError.js -> lib/main/errors/ClassNotExtendableError.js
src/main/errors/CodedError.js -> lib/main/errors/CodedError.js
src/main/errors/IllegalArgumentError.js -> lib/main/errors/IllegalArgumentError.js
src/main/errors/IllegalArgumentTypeError.js -> lib/main/errors/IllegalArgumentTypeError.js
src/main/errors/IllegalStateError.js -> lib/main/errors/IllegalStateError.js
src/main/errors/MethodNotImplementedError.js -> lib/main/errors/MethodNotImplementedError.js
src/main/errors/MissingRequiredArgumentError.js -> lib/main/errors/MissingRequiredArgumentError.js
src/main/errors/NonuniqueCriteriaError.js -> lib/main/errors/NonuniqueCriteriaError.js
src/main/errors/NotYetInitializedError.js -> lib/main/errors/NotYetInitializedError.js
src/main/errors/ObjectExistsError.js -> lib/main/errors/ObjectExistsError.js
src/main/errors/ObjectNotFoundError.js -> lib/main/errors/ObjectNotFoundError.js
src/main/errors/UnknownDiscriminatorError.js -> lib/main/errors/UnknownDiscriminatorError.js
src/main/errors/UnknownEnumError.js -> lib/main/errors/UnknownEnumError.js
src/main/errors/index.js -> lib/main/errors/index.js
src/main/index.js -> lib/main/index.js
src/main/logger/index.js -> lib/main/logger/index.js
src/main/package/pkg.js -> lib/main/package/pkg.js
src/main/require/index.js -> lib/main/require/index.js
src/main/services/ServiceSupport.js -> lib/main/services/ServiceSupport.js
src/main/services/index.js -> lib/main/services/index.js
src/main/services/returnsServiceResponse.js -> lib/main/services/returnsServiceResponse.js
src/main/string-utils/index.js -> lib/main/string-utils/index.js
Successfully compiled 37 files with Babel.

> @scispike/nodejs-support@2.1.0-pre.0 transpile-test /app
> babel --delete-dir-on-start --verbose --out-dir lib/test --copy-files src/test

src/test/unit/context/ClsHookedContext.spec.js -> lib/test/unit/context/ClsHookedContext.spec.js
src/test/unit/context/ZoneJsContext.spec.js -> lib/test/unit/context/ZoneJsContext.spec.js
src/test/unit/context/context-tests.js -> lib/test/unit/context/context-tests.js
src/test/unit/entities/DatePeriod.spec.js -> lib/test/unit/entities/DatePeriod.spec.js
src/test/unit/entities/Identifiable.spec.js -> lib/test/unit/entities/Identifiable.spec.js
src/test/unit/entities/Period.spec.js -> lib/test/unit/entities/Period.spec.js
src/test/unit/entities/Recurrence.spec.js -> lib/test/unit/entities/Recurrence.spec.js
src/test/unit/entities/_.merge.spec.js -> lib/test/unit/entities/_.merge.spec.js
src/test/unit/enums/DayOfWeek.spec.js -> lib/test/unit/enums/DayOfWeek.spec.js
src/test/unit/enums/Enumeration.spec.js -> lib/test/unit/enums/Enumeration.spec.js
src/test/unit/enums/ResponseStatus.spec.js -> lib/test/unit/enums/ResponseStatus.spec.js
src/test/unit/enums/TimeUnit.spec.js -> lib/test/unit/enums/TimeUnit.spec.js
src/test/unit/errors/CodedError.spec.js -> lib/test/unit/errors/CodedError.spec.js
src/test/unit/require/dirWithDirs/dir0/index.js -> lib/test/unit/require/dirWithDirs/dir0/index.js
src/test/unit/require/dirWithDirs/dir1/index.js -> lib/test/unit/require/dirWithDirs/dir1/index.js
src/test/unit/require/dirWithDirsWithNamesThatLookLikeFiles/dir0.js/index.js -> lib/test/unit/require/dirWithDirsWithNamesThatLookLikeFiles/dir0.js/index.js
src/test/unit/require/dirWithDirsWithNamesThatLookLikeFiles/dir1.json/index.js -> lib/test/unit/require/dirWithDirsWithNamesThatLookLikeFiles/dir1.json/index.js
src/test/unit/require/dirWithDirsWithNamesThatLookLikeFiles/index.js/index.js -> lib/test/unit/require/dirWithDirsWithNamesThatLookLikeFiles/index.js/index.js
src/test/unit/require/dirWithJsFiles/file0.js -> lib/test/unit/require/dirWithJsFiles/file0.js
src/test/unit/require/dirWithJsFiles/file1.js -> lib/test/unit/require/dirWithJsFiles/file1.js
src/test/unit/require/dirWithJsFiles/index.js -> lib/test/unit/require/dirWithJsFiles/index.js
src/test/unit/require/require.spec.js -> lib/test/unit/require/require.spec.js
src/test/unit/services/ServiceSupport.spec.js -> lib/test/unit/services/ServiceSupport.spec.js
src/test/unit/services/returnsServiceResponse.spec.js -> lib/test/unit/services/returnsServiceResponse.spec.js
src/test/unit/string-utils/index.spec.js -> lib/test/unit/string-utils/index.spec.js
src/test/unit/test-util.js -> lib/test/unit/test-util.js
Successfully compiled 26 files with Babel.

> @scispike/nodejs-support@2.1.0-pre.0 unit-integration /app
> nyc --check-coverage --statements 86 --branches 77 --functions 83 --lines 91 -x 'lib/test' --exclude-after-remap false mocha 'lib/test/unit/**/*.spec.js' 'lib/test/integration/**/*.spec.js'

Warning: Cannot find any files matching pattern "lib/test/integration/**/*.spec.js"


  ClsHookedTest
    ✓ should work with sync fn returning a value
    ✓ should work with awaiting sync fn returning a value
    ✓ should work with awaiting async fn returning a value
    ✓ should work with setTimeout
    ✓ should work with Promise.resolve
    ✓ should work with Promise.reject
    ✓ should work with async/await
    ✓ should give the same context when given the same name

  ZoneJsTest
    ✓ should work with sync fn returning a value
    ✓ should work with awaiting sync fn returning a value
    ✓ should work with awaiting async fn returning a value
    ✓ should work with setTimeout
    ✓ should work with Promise.resolve
    ✓ should work with Promise.reject
    ✓ should work with async/await
    ✓ should give the same context when given the same name

  _.merge
    ✓ should invoke inherited property methods correctly
    ✓ should invoke expressed property methods correctly
    ✓ should invoke expressed property methods correctly when used in ctors
    ✓ should invoke mutrait-expressed property methods correctly when used in ctors

  unit tests of DatePeriod
    ✓ should disallow invalid states
    ✓ should disallow invalid begin granularity
    ✓ should disallow invalid end granularity
    ✓ should contain or not correctly
    ✓ should overlap or not correctly
    ✓ should have a DatePeriod type

  unit tests of Identifiable
    ✓ should work

  unit tests of Period
    ✓ should disallow invalid states
    ✓ should contain or not correctly
    ✓ should overlap or not correctly
    ✓ should test length function
    ✓ should return false for a non-moment
    ✓ should have a Period type

  unit tests of Recurrence
    ✓ should work

  unit tests of DayOfWeek
    ✓ should calculate next & prev correctly
    ✓ should retrieve enum
    ✓ should fail to retrieve unknown enum

  unit tests of Enumeration
    ✓ should create a new enum
    ✓ should not allow extensions of enum classes

  unit tests of ResponseStatus
    ✓ should retrieve enum
    ✓ should fail to retrieve unknown enum

  unit tests of DayOfWeek
    ✓ should retrieve enum

  unit tests of CodedError
{"name":"CodedError","hostname":"ade26b9ce870","pid":179,"level":50,"err":{"message":"E_MY: boom","name":"MyError","stack":"MyError: E_MY: boom\n    at Context.it (/app/lib/test/unit/errors/CodedError.spec.js:25:15)\n    at callFn (/app/node_modules/mocha/lib/runnable.js:387:21)\n    at Test.Runnable.run (/app/node_modules/mocha/lib/runnable.js:379:7)\n    at Runner.runTest (/app/node_modules/mocha/lib/runner.js:535:10)\n    at /app/node_modules/mocha/lib/runner.js:653:12\n    at next (/app/node_modules/mocha/lib/runner.js:447:14)\n    at /app/node_modules/mocha/lib/runner.js:457:7\n    at next (/app/node_modules/mocha/lib/runner.js:362:14)\n    at Immediate._onImmediate (/app/node_modules/mocha/lib/runner.js:425:5)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)","code":"E_MY"},"msg":"E_MY: boom","time":"2019-11-13T15:44:37.524Z","v":0}
    ✓ should have code & no name or cause
{"name":"CodedError","hostname":"ade26b9ce870","pid":179,"level":50,"err":{"message":"E_MY: boom: E_MY_ERROR_CAUSE: because many badness so high","name":"MyError","stack":"MyError: E_MY: boom: E_MY_ERROR_CAUSE: because many badness so high\n    at Context.it (/app/lib/test/unit/errors/CodedError.spec.js:50:15)\n    at callFn (/app/node_modules/mocha/lib/runnable.js:387:21)\n    at Test.Runnable.run (/app/node_modules/mocha/lib/runnable.js:379:7)\n    at Runner.runTest (/app/node_modules/mocha/lib/runner.js:535:10)\n    at /app/node_modules/mocha/lib/runner.js:653:12\n    at next (/app/node_modules/mocha/lib/runner.js:447:14)\n    at /app/node_modules/mocha/lib/runner.js:457:7\n    at next (/app/node_modules/mocha/lib/runner.js:362:14)\n    at Immediate._onImmediate (/app/node_modules/mocha/lib/runner.js:425:5)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)","code":"E_MY"},"msg":"E_MY: boom: E_MY_ERROR_CAUSE: because many badness so high","time":"2019-11-13T15:44:37.527Z","v":0}
    ✓ should have a cause and code as name
{"name":"CodedError","hostname":"ade26b9ce870","pid":179,"level":50,"err":{"message":"E_MY: E_MY_ERROR_CAUSE","name":"MyError","stack":"MyError: E_MY: E_MY_ERROR_CAUSE\n    at Context.it (/app/lib/test/unit/errors/CodedError.spec.js:73:15)\n    at callFn (/app/node_modules/mocha/lib/runnable.js:387:21)\n    at Test.Runnable.run (/app/node_modules/mocha/lib/runnable.js:379:7)\n    at Runner.runTest (/app/node_modules/mocha/lib/runner.js:535:10)\n    at /app/node_modules/mocha/lib/runner.js:653:12\n    at next (/app/node_modules/mocha/lib/runner.js:447:14)\n    at /app/node_modules/mocha/lib/runner.js:457:7\n    at next (/app/node_modules/mocha/lib/runner.js:362:14)\n    at Immediate._onImmediate (/app/node_modules/mocha/lib/runner.js:425:5)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)","code":"E_MY"},"msg":"E_MY: E_MY_ERROR_CAUSE","time":"2019-11-13T15:44:37.528Z","v":0}
    ✓ should work with no args
{"name":"CodedError","hostname":"ade26b9ce870","pid":179,"level":50,"err":{"message":"E_SUB","name":"SubError","stack":"SubError: E_SUB\n    at Context.it (/app/lib/test/unit/errors/CodedError.spec.js:92:15)\n    at callFn (/app/node_modules/mocha/lib/runnable.js:387:21)\n    at Test.Runnable.run (/app/node_modules/mocha/lib/runnable.js:379:7)\n    at Runner.runTest (/app/node_modules/mocha/lib/runner.js:535:10)\n    at /app/node_modules/mocha/lib/runner.js:653:12\n    at next (/app/node_modules/mocha/lib/runner.js:447:14)\n    at /app/node_modules/mocha/lib/runner.js:457:7\n    at next (/app/node_modules/mocha/lib/runner.js:362:14)\n    at Immediate._onImmediate (/app/node_modules/mocha/lib/runner.js:425:5)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)","code":"E_SUB"},"msg":"E_SUB","time":"2019-11-13T15:44:37.531Z","v":0}
    ✓ should work with a supererror & no name
{"name":"CodedError","hostname":"ade26b9ce870","pid":179,"level":50,"err":{"message":"E_MY_ERROR: boom","name":"MyError","stack":"MyError: E_MY_ERROR: boom\n    at Context.it (/app/lib/test/unit/errors/CodedError.spec.js:115:15)\n    at callFn (/app/node_modules/mocha/lib/runnable.js:387:21)\n    at Test.Runnable.run (/app/node_modules/mocha/lib/runnable.js:379:7)\n    at Runner.runTest (/app/node_modules/mocha/lib/runner.js:535:10)\n    at /app/node_modules/mocha/lib/runner.js:653:12\n    at next (/app/node_modules/mocha/lib/runner.js:447:14)\n    at /app/node_modules/mocha/lib/runner.js:457:7\n    at next (/app/node_modules/mocha/lib/runner.js:362:14)\n    at Immediate._onImmediate (/app/node_modules/mocha/lib/runner.js:425:5)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)","code":"E_MY_ERROR"},"msg":"E_MY_ERROR: boom","time":"2019-11-13T15:44:37.532Z","v":0}
    ✓ should have name, code & no cause
{"name":"CodedError","hostname":"ade26b9ce870","pid":179,"level":50,"err":{"message":"E_MY: boom","name":"MyError","stack":"MyError: E_MY: boom\n    at Context.it (/app/lib/test/unit/errors/CodedError.spec.js:132:15)\n    at callFn (/app/node_modules/mocha/lib/runnable.js:387:21)\n    at Test.Runnable.run (/app/node_modules/mocha/lib/runnable.js:379:7)\n    at Runner.runTest (/app/node_modules/mocha/lib/runner.js:535:10)\n    at /app/node_modules/mocha/lib/runner.js:653:12\n    at next (/app/node_modules/mocha/lib/runner.js:447:14)\n    at /app/node_modules/mocha/lib/runner.js:457:7\n    at next (/app/node_modules/mocha/lib/runner.js:362:14)\n    at Immediate._onImmediate (/app/node_modules/mocha/lib/runner.js:425:5)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)","code":"E_MY"},"msg":"E_MY: boom","time":"2019-11-13T15:44:37.533Z","v":0}
    ✓ should have name & no cause
{"name":"CodedError","hostname":"ade26b9ce870","pid":179,"level":50,"err":{"message":"E_MY: boom: E_MY_CAUSE: because many badness so high","name":"MyError","stack":"MyError: E_MY: boom: E_MY_CAUSE: because many badness so high\n    at Context.it (/app/lib/test/unit/errors/CodedError.spec.js:158:15)\n    at callFn (/app/node_modules/mocha/lib/runnable.js:387:21)\n    at Test.Runnable.run (/app/node_modules/mocha/lib/runnable.js:379:7)\n    at Runner.runTest (/app/node_modules/mocha/lib/runner.js:535:10)\n    at /app/node_modules/mocha/lib/runner.js:653:12\n    at next (/app/node_modules/mocha/lib/runner.js:447:14)\n    at /app/node_modules/mocha/lib/runner.js:457:7\n    at next (/app/node_modules/mocha/lib/runner.js:362:14)\n    at Immediate._onImmediate (/app/node_modules/mocha/lib/runner.js:425:5)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)","code":"E_MY"},"msg":"E_MY: boom: E_MY_CAUSE: because many badness so high","time":"2019-11-13T15:44:37.534Z","v":0}
    ✓ should have a cause and code as name
{"name":"CodedError","hostname":"ade26b9ce870","pid":179,"level":50,"err":{"message":"E_MY: E_MY_CAUSE","name":"MyError","stack":"MyError: E_MY: E_MY_CAUSE\n    at Context.it (/app/lib/test/unit/errors/CodedError.spec.js:183:15)\n    at callFn (/app/node_modules/mocha/lib/runnable.js:387:21)\n    at Test.Runnable.run (/app/node_modules/mocha/lib/runnable.js:379:7)\n    at Runner.runTest (/app/node_modules/mocha/lib/runner.js:535:10)\n    at /app/node_modules/mocha/lib/runner.js:653:12\n    at next (/app/node_modules/mocha/lib/runner.js:447:14)\n    at /app/node_modules/mocha/lib/runner.js:457:7\n    at next (/app/node_modules/mocha/lib/runner.js:362:14)\n    at Immediate._onImmediate (/app/node_modules/mocha/lib/runner.js:425:5)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)","code":"E_MY"},"msg":"E_MY: E_MY_CAUSE","time":"2019-11-13T15:44:37.535Z","v":0}
    ✓ should work with no args
{"name":"CodedError","hostname":"ade26b9ce870","pid":179,"level":50,"err":{"message":"E_SUB2","name":"Sub2Error","stack":"Sub2Error: E_SUB2\n    at Context.it (/app/lib/test/unit/errors/CodedError.spec.js:206:15)\n    at callFn (/app/node_modules/mocha/lib/runnable.js:387:21)\n    at Test.Runnable.run (/app/node_modules/mocha/lib/runnable.js:379:7)\n    at Runner.runTest (/app/node_modules/mocha/lib/runner.js:535:10)\n    at /app/node_modules/mocha/lib/runner.js:653:12\n    at next (/app/node_modules/mocha/lib/runner.js:447:14)\n    at /app/node_modules/mocha/lib/runner.js:457:7\n    at next (/app/node_modules/mocha/lib/runner.js:362:14)\n    at Immediate._onImmediate (/app/node_modules/mocha/lib/runner.js:425:5)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)","code":"E_SUB2"},"msg":"E_SUB2","time":"2019-11-13T15:44:37.537Z","v":0}
    ✓ should work with a supererror, a subclass & a subclass subclass
{"name":"CodedError","hostname":"ade26b9ce870","pid":179,"level":50,"err":{"message":"E_SUB","name":"Sub","stack":"Sub: E_SUB\n    at Context.it (/app/lib/test/unit/errors/CodedError.spec.js:229:15)\n    at callFn (/app/node_modules/mocha/lib/runnable.js:387:21)\n    at Test.Runnable.run (/app/node_modules/mocha/lib/runnable.js:379:7)\n    at Runner.runTest (/app/node_modules/mocha/lib/runner.js:535:10)\n    at /app/node_modules/mocha/lib/runner.js:653:12\n    at next (/app/node_modules/mocha/lib/runner.js:447:14)\n    at /app/node_modules/mocha/lib/runner.js:457:7\n    at next (/app/node_modules/mocha/lib/runner.js:362:14)\n    at Immediate._onImmediate (/app/node_modules/mocha/lib/runner.js:425:5)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)","code":"E_SUB"},"msg":"E_SUB","time":"2019-11-13T15:44:37.539Z","v":0}
    ✓ should work with named error & supererror
    ✓ should return correctly from isInstance

  req
    ✓ should require all .js files (42ms)
    ✓ should require all .js files except index.js
    ✓ should require all dirs
    ✓ should require all .json files

  unit tests of @returnsServiceResponse
    ✓ should return successful response
    ✓ should return error response

  unit tests of ServiceSupport
    ✓ should create service response from dto
    ✓ should create service response from error

  unit tests of string-utils
    ✓ should convert camel case to snake
    ✓ should convert snake to camel case


  63 passing (316ms)

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|

> @scispike/nodejs-support@2.1.0-pre.0 postunit-integration /app
> run-s report


> @scispike/nodejs-support@2.1.0-pre.0 report /app
> nyc report --reporter=html


> @scispike/nodejs-support@2.1.0-pre.0 lint /app
> standard --verbose 'src/**/*.js'

standard: Unexpected linter output:

TypeError: Cannot read property 'range' of null
Occurred while linting /app/src/main/entities/DatePeriod.js:27
    at SourceCode.getTokenBefore (/app/node_modules/eslint/lib/source-code/token-store/index.js:303:18)
    at checkSpacingBefore (/app/node_modules/eslint/lib/rules/template-curly-spacing.js:60:42)
    at TemplateElement (/app/node_modules/eslint/lib/rules/template-curly-spacing.js:119:17)
    at listeners.(anonymous function).forEach.listener (/app/node_modules/eslint/lib/linter/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/app/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/app/node_modules/eslint/lib/linter/node-event-generator.js:253:26)
    at NodeEventGenerator.applySelectors (/app/node_modules/eslint/lib/linter/node-event-generator.js:282:22)
    at NodeEventGenerator.enterNode (/app/node_modules/eslint/lib/linter/node-event-generator.js:296:14)
    at CodePathAnalyzer.enterNode (/app/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:646:23)

If you think this is a bug in `standard`, open an issue: https://github.com/standard/standard/issues
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @scispike/nodejs-support@2.1.0-pre.0 lint: `standard --verbose 'src/**/*.js'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @scispike/nodejs-support@2.1.0-pre.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-11-13T15_44_49_163Z-debug.log
ERROR: "lint" exited with 1.
npm ERR! Test failed.  See above for more details.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @scispike/nodejs-support@2.1.0-pre.0 build: `npm install && npm test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @scispike/nodejs-support@2.1.0-pre.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-11-13T15_44_49_232Z-debug.log
```

**Comment by mightyiam** [comment]
@matthewadams could you please see whether it seems like one of the following?
https://github.com/babel/babel-eslint/issues/799
https://github.com/babel/babel-eslint/issues/741

**Comment by matthewadams** [comment]
@mightyiam As suggested in babel/babel-eslint#799, running `npm i @babel/types @babel/traverse --save-dev` fixed the problem!  So strange that it worked on macOS but failed on Linux.  #weird

**Comment by mightyiam** [comment]
Happy to learn that. Thank you for informing.
