### ISSUE TITLE
start standard with vscode got erro,and Code lint failure

### ISSUE THREAD

**Issue by yuanmaole** [standard/standard#1504]
I got an err when i start standart with vscode:
JavaScript Standard Style server is running.
[Info  - 11:53:27 AM] JavaScript Standard Style library loaded from: /Users/mollet/Work/LMT/LMT_RN/node_modules/standard/index.js
[Error - 11:53:29 AM] 
Failed to load plugin 'js' declared in 'CLIOptions': Cannot find module 'eslint-plugin-js'
Require stack:
- /Users/mollet/Work/LMT/LMT_RN/node_modules/standard/__placeholder__.js
Happend while validating /Users/mollet/Work/LMT/LMT_RN/src/views/Margin/VolInput.js
This can happen for a couple of reasons:
1. The plugin name is spelled incorrectly in JavaScript Standard Style configuration.
2. If JavaScript Standard Style is installed globally, then make sure 'eslint-plugin-js' is installed globally as well.
3. If JavaScript Standard Style is installed locally, then 'eslint-plugin-js' isn't installed correctly.
Error: Failed to load plugin 'js' declared in 'CLIOptions': Cannot find module 'eslint-plugin-js'
Require stack:
- /Users/mollet/Work/LMT/LMT_RN/node_modules/standard/__placeholder__.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Function.resolve (internal/modules/cjs/helpers.js:74:19)
    at Object.resolve (/Users/mollet/Work/LMT/LMT_RN/node_modules/eslint/lib/shared/relative-module-resolver.js:44:50)
    at ConfigArrayFactory._loadPlugin (/Users/mollet/Work/LMT/LMT_RN/node_modules/eslint/lib/cli-engine/config-array-factory.js:959:39)
    at /Users/mollet/Work/LMT/LMT_RN/node_modules/eslint/lib/cli-engine/config-array-factory.js:848:33
    at Array.reduce (<anonymous>)
    at ConfigArrayFactory._loadPlugins (/Users/mollet/Work/LMT/LMT_RN/node_modules/eslint/lib/cli-engine/config-array-factory.js:844:22)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/mollet/Work/LMT/LMT_RN/node_modules/eslint/lib/cli-engine/config-array-factory.js:667:32)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/mollet/Work/LMT/LMT_RN/node_modules/eslint/lib/cli-engine/config-array-factory.js:596:20) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/mollet/Work/LMT/LMT_RN/node_modules/standard/__placeholder__.js'
  ],
  messageTemplate: 'plugin-missing',
  messageData: {
    pluginName: 'eslint-plugin-js',
    resolvePluginsRelativeTo: '/Users/mollet/Work/LMT/LMT_RN/node_modules/standard',
    importerName: 'CLIOptions'
  }
}
i try to install the 'eslint-plugin-js ' with 'npm install  eslint-plugin-js --dev' but got ''eslint-plugin-js@latest' is not in the npm registry.'

**Comment by mightyiam** [comment]
@yuanmaole thank you for using Standaard. I'd love to help you but I am missing some important details. Please new issue that includes the details that are asked for in the [new issue](https://github.com/standard/standard/issues/new/choose) template.

**Comment by yuanmaole** [comment]
@mightyiam I using standard with vscode  successful now，but i want change some erro  to waring such as camel case or no-unused-vars
