### ISSUE TITLE
Some interpolation leads to "Cannot read property 'range' of null" error

### ISSUE THREAD

**Issue by searls** [standard/standard#1549]
**What version of this package are you using?**

14.3.4

**What operating system, Node.js, and npm version?**

On macOS: 

```
node -v
v14.1.0
npm -v
6.14.4
```

**What happened?**

Given `foo.js`:

```js
function click(selector) {
  return () =>
    document.querySelector(`#app ${selector}`)?.click()
}
```

This error came back:

```
$ yarn run standard foo.js 
yarn run v1.22.4
$ /Users/justin/code/searls/kamesame/node_modules/.bin/standard foo.js
standard: Unexpected linter output:

TypeError: Cannot read property 'range' of null
Occurred while linting /Users/justin/code/searls/kamesame/foo.js:3
    at SourceCode.getTokenBefore (/Users/justin/code/searls/kamesame/node_modules/eslint/lib/source-code/token-store/index.js:298:18)
    at checkSpacingBefore (/Users/justin/code/searls/kamesame/node_modules/eslint/lib/rules/template-curly-spacing.js:60:42)
    at TemplateElement (/Users/justin/code/searls/kamesame/node_modules/eslint/lib/rules/template-curly-spacing.js:119:17)
    at /Users/justin/code/searls/kamesame/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/justin/code/searls/kamesame/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/justin/code/searls/kamesame/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/Users/justin/code/searls/kamesame/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (/Users/justin/code/searls/kamesame/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (/Users/justin/code/searls/kamesame/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:634:23)

If you think this is a bug in `standard`, open an issue: https://github.com/standard/standard/issues
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Changing from `${selector}` interpolation to just passing `selector` resolves the error.

**Comment by feross** [comment]
Thanks for the bug report. I can't reproduce this issue with a `foo.js` containing just the code you posted.

@searls Can you try again using `standard` 15.0.0 which was released two days ago? There's a decent chance that the bug is fixed in that release?

**Comment by searls** [comment]
Huzzah! 15 works. Great job as always, @feross & friends 💖
