### ISSUE TITLE
Error: No files matching '.' were found.

### ISSUE THREAD

**Issue by krave1986** [standard/standard#1749]
**What version of this package are you using?**
standard@16.0.4
**What operating system, Node.js, and npm version?**
OS: Ubuntu 64
Node.js: v12.22.7
npm: 6.14.15

**What happened?**
If there is no file to be checked in the project, this error will be raised.

> > my-package@1.0.0 lint /workspaces/my-package
> > standard
> 
> standard: Unexpected linter output:
> 
> Error: No files matching '.' were found.
>     at FileEnumerator.iterateFiles (/workspaces/my-package/node_modules/eslint/lib/cli-engine/file-enumerator.js:317:27)
>     at iterateFiles.next (<anonymous>)
>     at CLIEngine.executeOnFiles (/workspaces/my-package/node_modules/eslint/lib/cli-engine/cli-engine.js:770:48)
>     at Linter.lintFiles (/workspaces/my-package/node_modules/standard-engine/index.js:117:59)
>     at Object.Cli [as cli] (/workspaces/my-package/node_modules/standard-engine/bin/cmd.js:103:14)
>     at Object.<anonymous> (/workspaces/my-package/node_modules/standard/bin/cmd.js:9:30)
>     at Module._compile (internal/modules/cjs/loader.js:999:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
>     at Module.load (internal/modules/cjs/loader.js:863:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
> 
> If you think this is a bug in `standard`, open an issue: https://github.com/standard/standard/issues
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! my-package@1.0.0 lint: `standard`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the my-package@1.0.0 lint script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2021-11-20T13_13_54_969Z-debug.log

**What did you expect to happen?**
There is no output.

**Are you willing to submit a pull request to fix this bug?**
Yes.

**Comment by yassin-assim** [comment]
Same issue with react app

What version of this package are you using?
standard@16.0.4

What operating system, Node.js, and npm version?
OS: MacOs Monterey
Node.js: v14.17.1
npm: 8.2.0

package.json :
{
    "react": "^17.0.2",
    "react-scripts": "4.0.3",
    "typescript": "^4.1.2",
},
  "devDependencies": {
    "ts-standard": "^11.0.0"
  }

**Comment by jimmywarting** [comment]
extension-less import is an anti pattern now days... esm explicit requires them.

**Comment by krave1986** [comment]
@jimmywarting Do you have some materials to support your point? Why those imports are anti pattern?
