### ISSUE TITLE
Cannot read properties of null (reading 'value')

### ISSUE THREAD

**Issue by smvilar** [standard/standard#1801]
**What version of this package are you using?**
16.0.4

**What operating system, Node.js, and npm version?**
macOS 12.3, node 14.19.0/16.14.2, npm 8.6.0

**What happened?**
I updated to the latest node and npm versions and then when running the linter on my project, this error happened:
```
TypeError: Cannot read properties of null (reading 'value')
Occurred while linting ***REDACTED***
    at checkSpacingBefore (***REDACTED***/node_modules/eslint/lib/rules/template-curly-spacing.js:52:24)
    at TemplateElement (***REDACTED***/node_modules/eslint/lib/rules/template-curly-spacing.js:136:17)
    at ***REDACTED***/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (***REDACTED***/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (***REDACTED***/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (***REDACTED***/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (***REDACTED***/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (***REDACTED***/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
    at ***REDACTED***/node_modules/eslint/lib/linter/linter.js:952:32
```

The line in question is (don't ask me why):
```js
variables: variables[`${type}Variables`],
```

**What did you expect to happen?**
To work normally.

**Are you willing to submit a pull request to fix this bug?**
Yup

**Comment by smvilar** [comment]
Nevermind, this was an error because I was using the deprecated `babel-eslint` as the parser, instead of the new `@babel/eslint-parser`. Did the change, it works.
