### ISSUE TITLE
pre-commit complains about keys/SSL cert from this repo?

### ISSUE THREAD

**Issue by gacallea** [standard/standard#1880]
Hi, I hope this is relevant here and wish it could help/be resolvable. If not, I'll try opening an issue at pre-commit.

**What version of this package are you using?**

`"standard": "^17.0.0",`

**What operating system, Node.js, and npm version?**

`macOS 12.6.2`

`node v18.13.0`

`npm 9.2.0`

`pre-commit 2.21.0`

**What happened?**

When I run `pre-commit autoupdate` or `pre-commit run --all-files` , pre-commit complains about unmatching SSL certificates for/from this very repo.

**What did you expect to happen?**

It used to work and just run fine and apply its rules. It's been warning me for a while, and now it has stopped working completely.

**Are you willing to submit a pull request to fix this bug?**

I would if I could. I can't do Js.

Here is my config `.pre-commit-config.yaml` :

```
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
        args: [--assume-in-merge]
      - id: check-symlinks
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/standard/standard
    rev: v17.0.0
    files: "./**/*.(js|jsx|ts|tsx|mjs|cjs)"
    hooks:
      - id: standard
        args: [--fix]
```

Here's an output:

```
$ pre-commit autoupdate
[WARNING] Unexpected key(s) present on https://github.com/standard/standard: files
Updating https://github.com/pre-commit/pre-commit-hooks ... already up to date.
Updating https://github.com/standard/standard ... already up to date.
```

```
$ pre-commit run --all-files
[WARNING] Unexpected key(s) present on https://github.com/standard/standard: files
[INFO] Installing environment for https://github.com/standard/standard.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/usr/local/opt/python@3.10/bin/python3.10', '-mnodeenv', '--prebuilt', '--clean-src', '/Users/gacallea/.cache/pre-commit/repoc1kllni1/node_env-default')
return code: 1
stdout: (none)
stderr:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1348, in do_open
        h.request(req.get_method(), req.selector, req.data, headers,
      File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1282, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1328, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1277, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1037, in _send_output
        self.send(msg)
      File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 975, in send
        self.connect()
      File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1454, in connect
        self.sock = self._context.wrap_socket(self.sock,
      File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 513, in wrap_socket
        return self.sslsocket_class._create(
      File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1071, in _create
        self.do_handshake()
      File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1342, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
        exec(code, run_globals)
      File "/usr/local/lib/python3.10/site-packages/nodeenv.py", line 1519, in <module>
        main()
      File "/usr/local/lib/python3.10/site-packages/nodeenv.py", line 1093, in main
        args.node = get_last_stable_node_version()
      File "/usr/local/lib/python3.10/site-packages/nodeenv.py", line 1026, in get_last_stable_node_version
        return _get_versions_json()[0]['version'].lstrip('v')
      File "/usr/local/lib/python3.10/site-packages/nodeenv.py", line 1002, in _get_versions_json
        response = urlopen('%s/index.json' % src_base_url)
      File "/usr/local/lib/python3.10/site-packages/nodeenv.py", line 624, in urlopen
        return urllib2.urlopen(req)
      File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 519, in open
        response = self._open(req, data)
      File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 536, in _open
        result = self._call_chain(self.handle_open, protocol, protocol +
      File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
        result = func(*args)
      File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1391, in https_open
        return self.do_open(http.client.HTTPSConnection, req,
      File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1351, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>

Check the log at /Users/gacallea/.cache/pre-commit/pre-commit.log
```

**Comment by LinusU** [comment]
I think that this is two unrelated problems, and the warning about Standard is that you have added `files` to a ["repository mapping"](https://pre-commit.com/#pre-commit-configyaml---repos), which doesn't have a `key` config.

**Comment by gacallea** [comment]
thank you @LinusU , removing `files` worked for the warning.

Regarding the python issue: I thought it was related sorry. Just found out that is a python issue, most probably with the brew version that has recently updated. Will open an issue there, as it is the first time this happens. In the past brew python has never complained. They may have forgotten to install certs with it.
