### ISSUE TITLE
Error: Cannot find module 'eslint-plugin-react'

### ISSUE THREAD

**Issue by MarkTiedemann** [standard/standard#949]
Using `npm@5.2.0` and `standard@10.0.2` together does not seem to work as an npm script. It works if I run it directly from the command line (on Windows).

`λ ll`
```
node_modules
package-lock.json
package.json
```

`λ type package.json`
```
{
  "name": "standard-npm-bug",
  "version": "0.1.0",
  "scripts": {
    "test": "standard"
  },
  "devDependencies": {
    "standard": "^10.0.2"
  }
}
```

`λ npm t`
```
> standard-npm-bug@0.1.0 test C:\dev\node\standard-npm-bug
> standard

standard: Unexpected linter output:

Error: Failed to load plugin react: Cannot find module 'eslint-plugin-react'
Referenced from: C:\dev\node\standard-npm-bug\node_modules\standard\eslintrc.json
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.load (C:\dev\node\standard-npm-bug\node_modules\eslint\lib\config\plugins.js:134:29)
    at Array.forEach (native)
    at Object.loadAll (C:\dev\node\standard-npm-bug\node_modules\eslint\lib\config\plugins.js:162:21)
    at load (C:\dev\node\standard-npm-bug\node_modules\eslint\lib\config\config-file.js:541:21)
    at configExtends.reduceRight (C:\dev\node\standard-npm-bug\node_modules\eslint\lib\config\config-file.js:424:36)
    at Array.reduceRight (native)
    at applyExtends (C:\dev\node\standard-npm-bug\node_modules\eslint\lib\config\config-file.js:408:28)
    at Object.load (C:\dev\node\standard-npm-bug\node_modules\eslint\lib\config\config-file.js:566:22)

If you think this is a bug in `standard`, open an issue: https://github.com/feross/standard/issues
npm ERR! Test failed.  See above for more details.
```

`λ npm -v`
```
5.2.0
```
`λ node -v`
```
v8.1.2
```

`λ ver`
```
Microsoft Windows [Version 10.0.15063]
```

**Comment by big-kahuna-burger** [comment]
Same here:

```bash
> authentic-ui@1.1.0 test /home/travis/build/big-kahuna-burger/authentic-ui
> node test/index.js && standard && npm run deps
standard: Unexpected linter output:
Error: Failed to load plugin import: Cannot find module 'eslint-plugin-import'
Referenced from: /home/travis/build/big-kahuna-burger/authentic-ui/node_modules/standard/eslintrc.json...
```
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04

**Comment by klaemo** [comment]
I'm encountering the same problem. Not sure if it's related to standard though, because it only started happening with the latest npm version(s).
The packages all seem to be there, too:
![bildschirmfoto 2017-07-12 um 11 15 12](https://user-images.githubusercontent.com/778624/28110723-8beb794e-66f3-11e7-8d05-ca63cb046c72.png)

**Comment by lovell** [comment]
This was a [breaking change](https://github.com/npm/npm/pull/17678) in npm v5.2.0 that has now been [reverted](https://github.com/npm/npm/issues/17717). Use npm v5.1.0 as a workaround until v5.2.1 is available.

**Comment by MarkTiedemann** [comment]
`npm i -g npm@5.1.0 && rm -rf node_modules && npm i && npm t` worked. Thanks for the help!

**Comment by big-kahuna-burger** [comment]
@lovell cheers for figuring out. Appreciated.

**Comment by tensor5** [comment]
I have the same issue with npm v5.3.0.

**Comment by needim** [comment]
I updated eslint to 4.3.0 and it worked. fyi.

**Comment by AndrejGajdos** [comment]
@tensor5 me too
