### ISSUE TITLE
Range error? Not enough lines of code??

### ISSUE THREAD

**Issue by EGM** [standard/standard#997]
> node node_modules/standard/bin/cmd --fix && node node_modules/mocha/bin/mocha

standard: Unexpected linter output:

RangeError: Line number out of range (line 79 requested, but only 78 lines present).
    at SourceCode.getIndexFromLoc (/storage/emulated/0/AppProjects/dsalt/node_modules/eslint/lib/util/source-code.js:389:19)
    at Object.fix (/storage/emulated/0/AppProjects/dsalt/node_modules/eslint/lib/rules/no-multiple-empty-lines.js:116:52)
    at RuleContext.report (/storage/emulated/0/AppProjects/dsalt/node_modules/eslint/lib/rule-context.js:127:34)
    at Program:exit.allLines.reduce.concat.reduce (/storage/emulated/0/AppProjects/dsalt/node_modules/eslint/lib/rules/no-multiple-empty-lines.js:108:37)
    at Array.reduce (native)
    at EventEmitter.Program:exit (/storage/emulated/0/AppProjects/dsalt/node_modules/eslint/lib/rules/no-multiple-empty-lines.js:93:22)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.applySelector (/storage/emulated/0/AppProjects/dsalt/node_modules/eslint/lib/util/node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (/storage/emulated/0/AppProjects/dsalt/node_modules/eslint/lib/util/node-event-generator.js:294:22)

If you think this is a bug in `standard`, open an issue: https://github.com/standard/standard/issues
npm ERR! Test failed.  See above for more details.
code : 1 / signal : 0

**Comment by dein0s** [comment]
Just got the same exception. The reason was in extra spaces in the ending line.
