### ISSUE TITLE
Can't get it working with Flowtype

### ISSUE THREAD

**Issue by jaimeagudo** [standard/standard#999]
I have followed the instructions for https://standardjs.com/index.html#flow on node v8.6.0  

package.json
```
"standard": {
    "parser": "babel-eslint",
    "plugins": [
      "flowtype"
    ]
  },
..
"devDependencies": {
    "babel-eslint": "^8.0.1",
    "eslint": "^4.8.0",
    "eslint-plugin-flowtype": "^2.39.1",
}

```

`$standard`

```
standard: Unexpected linter output:

Error: Failed to load plugin flowtype: Cannot find module 'eslint-plugin-flowtype'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.load (/usr/local/lib/node_modules/standard/node_modules/eslint/lib/config/plugins.js:129:26)
    at Array.forEach (<anonymous>)
    at Object.loadAll (/usr/local/lib/node_modules/standard/node_modules/eslint/lib/config/plugins.js:151:21)
    at Config.getConfig (/usr/local/lib/node_modules/standard/node_modules/eslint/lib/config.js:305:17)
    at hashOfConfigFor (/usr/local/lib/node_modules/standard/node_modules/eslint/lib/cli-engine.js:599:41)
    at executeOnFile (/usr/local/lib/node_modules/standard/node_modules/eslint/lib/cli-engine.js:648:32)

If you think this is a bug in `standard`, open an issue: https://github.com/feross/standard/issues

```

Have tried everything, global, local installation with npm & yarn... am I missing something

**Comment by ematipico** [comment]
Duplicate of https://github.com/standard/standard/issues/984

**Comment by KalebPortillo** [comment]
same here, nothing in #984 worked

**Comment by frednomoon** [comment]
@feross having the same issue but it seems unclear what the correct approach should be. Tried also installing eslint-plugin-flowtype globally as well as standard and still have the same problem.
Installing both locally seems to clash with my global install of standard, so that doesnt work either.

Do I have to uninstall standard globally for this to work??
